In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Read in the data
df = pd.read_csv('/Users/changyichieh/Documents/Hot Jupiter/Hot_Jupiter_Github/hot_jupiter/Parmentier 2/PTprofile(20bar)(Hd209458b)(0103).csv')
df.columns

Index(['N', 'Gp', 'mu', 'R(J/(K*g))', 'tau', 'g(m/s^2)', 'beta', 'Betav1',
       'Betav2', 'Betav3', 'T_irr(K)', 'P_H(Pa)', 'Gv1', 'Gv2', 'Gv3',
       'Gamma1', 'Gamma2', 'sigma', 'P(Pa)', 'Kappa(m^2/kg)', 'T(K)', 'rho',
       'pkpt', 'pkpr', 'J1(W/m^2)', 'J2(W/m^2)', 'H1(W/m^2)', 'H2(W/m^2)',
       'C1', 'C3', 'GAMMA_0', 't_th'],
      dtype='object')

In [24]:
# Read in the data
new_df = pd.DataFrame()

new_df['N'] = df['N']
new_df['P'] = df['P(Pa)']


new_df['ak'] = df['P(Pa)']
new_df['bk'] = 0
new_df['ph'] = df['P(Pa)']/100
# pf is the midpoint pressure of each layer
new_df['pf'] = (new_df['P'] + new_df['P'].shift(1)) / 2
new_df.loc[0, 'pf'] = new_df.loc[0, 'P']/2  # or any other method you find suitable

# insert a N=0 row
new_df.loc[-1] = 0  # adding a row
new_df.index = new_df.index + 1  # shifting index
new_df = new_df.sort_index()  # sorting by index

new_df['pf']/=100

del new_df['P']
# del new_df['N']

new_df

     N         ak  bk         ph          pf
0    0        0.0   0      0.000      0.0000
1    1       10.0   0      0.100      0.0500
2    2       12.3   0      0.123      0.1115
3    3       15.1   0      0.151      0.1370
4    4       18.6   0      0.186      0.1685
..  ..        ...  ..        ...         ...
56  56   874000.0   0   8740.000   7925.0000
57  57  1080000.0   0  10800.000   9770.0000
58  58  1320000.0   0  13200.000  12000.0000
59  59  1630000.0   0  16300.000  14750.0000
60  60  2000000.0   0  20000.000  18150.0000

[61 rows x 5 columns]

In [28]:
# save the new_df to a space-separated text file
np.savetxt('/Users/changyichieh/Documents/Hot Jupiter/Hot_Jupiter_Github/hot_jupiter/Parmentier 2/model_levels_Hd209458b.txt', new_df,
            fmt=['%d', '%10.2f', '%10.2f', '%10.2f', '%10.2f'], delimiter='\t', header='N ak bk ph pf', comments='')